;;; surround-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from surround.el

(autoload 'surround-make-keymap "surround" "\
Create and return the keymap for surround.")
(autoload 'surround-mark-outer "surround" "\
Mark a pair including the pair characters defined by CHAR.

(fn CHAR)" t)
(autoload 'surround-mark-inner "surround" "\
Mark a pair excluding the pair characters defined by CHAR.

(fn CHAR)" t)
(autoload 'surround-mark "surround" "\
Mark text in a pair.  If CHAR is a closing character, mark pair also.

(fn CHAR)" t)
(autoload 'surround-kill-outer "surround" "\
Kill pair defined by CHAR and text within it.

(fn CHAR)" t)
(autoload 'surround-kill-inner "surround" "\
Kill text within pair defined by CHAR.

(fn CHAR)" t)
(autoload 'surround-kill "surround" "\
Kill text within a pair.  If CHAR is a closing character, kill pair also.

(fn CHAR)" t)
(autoload 'surround-insert "surround" "\
Surrounds region or current symbol with a pair defined by CHAR.

(fn CHAR)" t)
(autoload 'surround-delete "surround" "\
Deletes a pair defined by CHAR, leaving the contents.

(fn CHAR)" t)
(autoload 'surround-change "surround" "\
Replace OLD pair with NEW.

(fn OLD NEW)" t)
(register-definition-prefixes "surround" '("surround-"))

;;; End of scraped data

(provide 'surround-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; surround-autoloads.el ends here
