;;; tab-line-nerd-icons-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tab-line-nerd-icons.el

(defvar tab-line-nerd-icons-global-mode nil "\
Non-nil if Tab-Line-Nerd-Icons-Global mode is enabled.
See the `tab-line-nerd-icons-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `tab-line-nerd-icons-global-mode'.")
(custom-autoload 'tab-line-nerd-icons-global-mode "tab-line-nerd-icons" nil)
(autoload 'tab-line-nerd-icons-global-mode "tab-line-nerd-icons" "\
Add an icon to the label for tab-line tabs.

This is a global minor mode.  If called interactively, toggle the
`Tab-Line-Nerd-Icons-Global mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='tab-line-nerd-icons-global-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "tab-line-nerd-icons" '("tab-line-nerd-icons-"))

;;; End of scraped data

(provide 'tab-line-nerd-icons-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tab-line-nerd-icons-autoloads.el ends here
